<?php /** @var \Zaius\Engage\Block\Snippet $block */ ?>
<script type='text/javascript'>
    var zaius = window['zaius'] || (window['zaius'] = []);
    zaius.methods = ["initialize", "onload", "event", "entity", "identify", "anonymize"];
    zaius.factory = function (e) {
        return function () {
            var t = Array.prototype.slice.call(arguments);
            t.unshift(e);
            zaius.push(t);
            return zaius
        }
    };
    for (var i = 0; i < zaius.methods.length; i++) {
        var method = zaius.methods[i];
        zaius[method] = zaius.factory(method)
    }
    (function () {
        var e = document.createElement("script");
        e.type = "text/javascript";
        e.async = true;
        e.src = ("https:" === document.location.protocol ? "https://" : "http://") + "d1igp3oop3iho5.cloudfront.net/v2/<?php echo $this->getTrackingID(); ?>/zaius-min.js";
        var t = document.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(e, t)
    })();
    <?php foreach ($block->getEvents() as $event): ?>
    <?php echo $block->getEventJs($event) . "\n"; ?>
    <?php endforeach; ?>
</script>
