<?php /* @var $block \Zaius\Engage\Block\System\Config\BulkUpdatesButton */ ?>
<script>
    require([
        'jquery',
        'prototype',
    ], function (jQuery) {

        var syncSpan = jQuery('#bulk_span');

        function sync() {
            params = {};

            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                loaderArea: false,
                asynchronous: true,
                parameters: params,
                onCreate: function () {
                    syncSpan.find('.synced').hide();
                    syncSpan.find('.syncing').show();
                    jQuery('#bulk_message_span').text('');
                },
                onSuccess: function (response) {

                    console.log(response);

                    syncSpan.find('.syncing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success!';
                        syncSpan.find('.synced').show();
                    }
                    jQuery('#bulk_message_span').text(resultText);
                }
            });
        }

        jQuery('#bulk_btn').click(function () {
            sync();
        });
    });
</script>
<?php echo $block->getButtonHtml() ?>
<span class="sync-indicator" id="bulk_span">
    <img class="syncing" hidden="hidden" alt="Syncing" style="margin:0 5px"
         src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="synced" hidden="hidden" alt="Synced" style="margin:-3px 5px"
         src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="bulk_message_span"></span>
</span>